### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by Sofia-vig** [FacundoEG/Piedra-Papel-o-Tijera-Single-Player#1]
Hola! Lo estaba probando y encontré algunas cosas que no funcionan bien, por ejemplo cuando yo no elijo una jugada me dice que la pagina no existe, te dejo captura de como me aparece:
![Captura de pantalla de 2021-08-23 10-24-55](https://user-images.githubusercontent.com/76600032/130415791-6d44a8e9-059c-47f6-82c1-3226c5aa434e.png)
![Captura de pantalla de 2021-08-23 10-24-41](https://user-images.githubusercontent.com/76600032/130415786-a3abf563-43f5-44ba-bc7a-ca4c36981c32.png)
También estaba viendo, y a veces me hace jugar dos o tres veces antes de mostrarme el resultado, eso sucede cuando es un empate?
Fijate si podes corregir eso y volver a enviarlo, y recordar de enviar el link del repositorio de github, no de github pages. Saludoss!

**Comment by FacundoEG** [comment]
Hola Sofía! buenas!

Si evidentemente hay un error con la ruta cuando no se realiza ninguna jugada

Cuando la jugada se repite es porque hubo empate, pero voy a cambiarlo para que sea mas informativo.

Gracias por la review, saludos!
