### ISSUE TITLE
Muy buen juego!

### ISSUE THREAD

**Issue by Alvax10** [FacundoEG/Piedra-Papel-o-Tijera-Single-Player#2]
Buenas Facu, ahí estaba revisando tu código, y la única modificación que le haría sería en el contador de tiempo. En vez de que el tiempo se corte después de elegir una mano, haría que pasen los 3 segundos igual, así si el jugador quiere cambiar de mano antes de que se termine el tiempo, pueda hacerlo. Por lo otro estuvo todo bastante bien, me gustó la animación del contador y la página extra que le recuerda al jugador de elegir una mano, Felicitaciones!

**Comment by FacundoEG** [comment]
Hola Alvaro! no me había percatado de eso! lo tendré en cuenta para modificarlo en breve.

Gracias por tu review! saludos!

**Comment by Alvax10** [comment]
Perfecto, tambien consideralo para el próximo módulo que va a ser
multijugador!!
